let soundsPath = './assets/static/sounds',
  imgPath = './assets/static/img/test_images/';

export var mitigationStrategies = [
  { name: 'Eat less meat', description: 'Think of the cows' },
  { name: 'Burn down all data centers', description: '' },
  { name: 'Turn off appliances when not in use', description: '' },
  { name: 'Recycle more', description: '' },
  {
    name: 'Reshape our cities to be less car-dependent',
    description:
      'Measures like increasing allowed density, widening sidewalks, removing minimum-parking rules for new developments, etc.',
  },
  {
    name: 'An all-encompassing high-rate carbon-tax',
    description:
      'This will make most products more expensive, but could also incentivize a green economy.',
  },
  { name: 'Do nothing and just watch the world burn', description: '' },
  { name: 'Hope for a deus ex machina', description: '' },
];
export var testData = {
  questions: [
    {
      stanzaCode: '01-p2-1',
      videoId: 'vowylgLbmXs',
      imageUrl: require(imgPath + '00.png'),
      AudioAUrl: require(`${soundsPath}/Poema-2a_01.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-2b_01.mp3`),
      videoCode: 'b',
      imgCode: 'a',
    },
    {
      stanzaCode: '02-p2-2',
      videoId: 'cnP_ptQlTwo',
      imageUrl: require(imgPath + '01.png'),
      AudioAUrl: require(`${soundsPath}/Poema-2a_02.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-2b_02.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: '03-p2-3',
      videoId: 'uj0OFVhKPHA',
      imageUrl: require(imgPath + '02.png'),
      AudioAUrl: require(`${soundsPath}/Poema-2a_03.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-2b_03.mp3`),
      videoCode: 'a',
      imgCode: 'a',
    },
    {
      stanzaCode: '04-p2-4',
      videoId: 'F3LKMYsr3QU',
      imageUrl: require(imgPath + '03.png'),
      AudioAUrl: require(`${soundsPath}/Poema-2a_04.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-2b_04.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: '05-p1-1',
      videoId: '7LsxvFoJPhQ',
      imageUrl: require(imgPath + '04.png'),
      AudioAUrl: require(`${soundsPath}/Poema-1a_01.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-1b_01.mp3`),
      videoCode: 'a',
      imgCode: 'a',
    },
    {
      stanzaCode: '06-p1-2',
      videoId: 'rcN5TFeZ_-k',
      imageUrl: require(imgPath + '05.png'),
      AudioAUrl: require(`${soundsPath}/Poema-1a_02.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-1b_02.mp3`),
      videoCode: 'b',
      imgCode: 'b',
    },
    {
      stanzaCode: '07-p1-3',
      videoId: 'bB4Aiw0k9A0',
      imageUrl: require(imgPath + '06.png'),
      AudioAUrl: require(`${soundsPath}/Poema-1a_03.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-1b_03.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: '08-p4-1',
      videoId: '-4j-mXkORaE',
      imageUrl: require(imgPath + '07.png'),
      AudioAUrl: require(`${soundsPath}/Poema-4a_01.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-4b_01.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: '09-p4-2',
      videoId: 'Uimi_eZ9-dY',
      imageUrl: require(imgPath + '08.png'),
      AudioAUrl: require(`${soundsPath}/Poema-4a_02.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-4b_02.mp3`),
      videoCode: 'b',
      imgCode: 'a',
    },
    {
      stanzaCode: '10-p4-3',
      videoId: 'Xx4LaNgAQ_k',
      imageUrl: require(imgPath + '09.png'),
      AudioAUrl: require(`${soundsPath}/Poema-4a_03.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-4b_03.mp3`),
      videoCode: 'a',
      imgCode: 'a',
    },
    {
      stanzaCode: '11-p4-4',
      videoId: 'CmgVzQLnPyI',
      imageUrl: require(imgPath + '10.png'),
      AudioAUrl: require(`${soundsPath}/Poema-4a_04.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-4b_04.mp3`),
      videoCode: 'b',
      imgCode: 'a',
    },
    {
      stanzaCode: '12-p3-1',
      videoId: 'vTaaukE1YI4',
      imageUrl: require(imgPath + '11.png'),
      AudioAUrl: require(`${soundsPath}/Poema-3a_01.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-3b_01.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: '13-p3-2',
      videoId: 'SAUsdCjNqlM',
      imageUrl: require(imgPath + '12.png'),
      AudioAUrl: require(`${soundsPath}/Poema-3a_02.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-3b_02.mp3`),
      videoCode: 'b',
      imgCode: 'a',
    },
    {
      stanzaCode: '14-p3-3',
      videoId: 'Eubv-f1qIA8',
      imageUrl: require(imgPath + '13.png'),
      AudioAUrl: require(`${soundsPath}/Poema-3a_03.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-3b_03.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
    {
      stanzaCode: 'p3-4',
      videoId: 'VMndLfrapa4',
      imageUrl: require(imgPath + '14.png'),
      AudioAUrl: require(`${soundsPath}/Poema-3a_04.mp3`),
      AudioBUrl: require(`${soundsPath}/Poema-3b_04.mp3`),
      videoCode: 'a',
      imgCode: 'b',
    },
  ],
};
